# Generated by Django 2.2.8 on 2019-12-16 01:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_squashed_0010_auto_20191215_0731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
