version: "3.2"

services:
  postgres:
    build:
      context: docker/postgres/
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis
    hostname: "redis"
    ports:
      - "6379:6379"

  django:
    build:
      context: docker/django/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis


volumes:
  postgresql:
  postgresql_data:
