# Generated by Django 3.2 on 2021-04-24 03:22

import codertheory.utils.custom_fields
import codertheory.utils.generator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', codertheory.utils.custom_fields.NanoIDField(auto_created=True, default=codertheory.utils.generator.generate_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', codertheory.utils.custom_fields.NanoIDField(auto_created=True, default=codertheory.utils.generator.generate_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.CharField(max_length=1000)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', codertheory.utils.custom_fields.NanoIDField(auto_created=True, default=codertheory.utils.generator.generate_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
            ],
            options={
                'order_with_respect_to': 'option',
            },
        ),
        migrations.AddConstraint(
            model_name='pollvote',
            constraint=models.UniqueConstraint(fields=('poll', 'ip'), name='Unique IP Per Poll'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='polloption',
            order_with_respect_to='poll',
        ),
        migrations.AddConstraint(
            model_name='polloption',
            constraint=models.UniqueConstraint(fields=('option', 'poll'), name='unique_option'),
        ),
    ]
