# Generated by Django 3.2.3 on 2021-06-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0002_auto_20210526_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
