# Generated by Django 3.0.8 on 2020-08-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shiritori', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='lives',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
