# Generated by Django 3.0.8 on 2020-08-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shiritori', '0002_player_lives'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='timer',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
