# Generated by Django 3.1.2 on 2020-11-29 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shiritori', '0004_auto_20200903_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiritorigame',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_winner',
                                    to='shiritori.shiritoriplayer'),
        ),
    ]
