# Generated by Django 3.1.5 on 2021-02-05 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiritori', '0006_auto_20201204_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiritorigame',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_player_game', to='shiritori.shiritoriplayer'),
        ),
        migrations.AlterField(
            model_name='shiritorigame',
            name='password',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shiritorigame',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_winner', to='shiritori.shiritoriplayer'),
        ),
    ]
