# Generated by Django 3.1.5 on 2021-02-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiritori', '0008_remove_shiritorigame_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiritorigame',
            name='player_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
