# Generated by Django 3.1.5 on 2021-02-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiritori', '0009_shiritorigame_player_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiritorigame',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
