# Generated by Django 3.1.5 on 2021-02-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiritori', '0010_shiritorigame_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiritorigame',
            name='timer_expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
