# Generated by Django 3.2.4 on 2021-06-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shiritori', '0014_alter_shiritorigame_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiritorigame',
            name='password',
        ),
        migrations.AddField(
            model_name='shiritorigame',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
