# Generated by Django 3.2.4 on 2021-07-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shiritori', '0015_auto_20210624_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiritoriplayer',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
