# Generated by Django 3.2.4 on 2021-07-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shiritori', '0016_alter_shiritoriplayer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiritorigameword',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
