# Generated by Django 3.1.2 on 2020-11-14 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('iceteabot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NickName',
            new_name='DiscordNickName',
        ),
    ]
