# Generated by Django 3.1.5 on 2021-01-27 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iceteabot', '0003_auto_20201204_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
