# Generated by Django 3.1 on 2020-09-02 16:43

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=15)),
                ('background_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('text_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DisplayBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False)),
                ('image',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.bannerimage')),
                ('primary_button',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to='website.bannerbutton')),
                ('secondary_button',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.bannerbutton')),
            ],
        ),
    ]
