# Generated by Django 3.1.5 on 2021-01-28 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaybanner',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.bannerimage'),
        ),
        migrations.AlterField(
            model_name='displaybanner',
            name='primary_button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.bannerbutton'),
        ),
        migrations.AlterField(
            model_name='displaybanner',
            name='secondary_button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.bannerbutton'),
        ),
    ]
